name: Deploy SpeechAgent with Velopack

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy (e.g., 0.0.2)'
        required: true
        default: '0.0.2'

env:
  DOTNET_VERSION: '8.0'
  PROJECT_NAME: 'SpeechAgent'
  RUNTIME: 'win-x64'
  DOTNET_CLI_UI_LANGUAGE: 'ko-KR'
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 'false'

jobs:
  deploy:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Set Korean locale with UTF-8 encoding
      run: |
        $culture = [System.Globalization.CultureInfo]::CreateSpecificCulture("ko-KR")
        [System.Threading.Thread]::CurrentThread.CurrentCulture = $culture
        [System.Threading.Thread]::CurrentThread.CurrentUICulture = $culture
        echo "LANG=ko_KR.UTF-8" >> $env:GITHUB_ENV
        echo "LC_ALL=ko_KR.UTF-8" >> $env:GITHUB_ENV
        $OutputEncoding = [System.Text.Encoding]::UTF8
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
        [Console]::InputEncoding = [System.Text.Encoding]::UTF8
        echo "Korean locale with UTF-8 encoding configured"
      shell: pwsh      

    - name: Install Velopack CLI
      run: dotnet tool install -g vpk

    - name: Extract version from tag or input
      id: version
      run: |
        if ("${{ github.event_name }}" -eq "push") {
          $version = "${{ github.ref_name }}" -replace "^v", ""
        } else {
          $version = "${{ github.event.inputs.version }}"
        }
        echo "VERSION=$version" >> $env:GITHUB_OUTPUT
        echo "Version: $version"
      shell: pwsh

    - name: Update project version
      run: |
        $version = "${{ steps.version.outputs.VERSION }}"
        $csprojPath = "${{ env.PROJECT_NAME }}.csproj"
        $content = Get-Content $csprojPath -Raw -Encoding UTF8
        $updatedContent = $content -replace '<VersionPrefix>.*</VersionPrefix>', "<VersionPrefix>$version</VersionPrefix>"
        Set-Content $csprojPath -Value $updatedContent -Encoding UTF8
        echo "Updated version to: $version"
      shell: pwsh

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_NAME }}.csproj

    - name: Publish application
      run: |
        dotnet publish ${{ env.PROJECT_NAME }}.csproj `
          --configuration Release `
          --self-contained `
          --runtime ${{ env.RUNTIME }} `
          --output ./publish `
          /p:PublishSingleFile=true `
          /p:IncludeAllContentForSelfExtract=true `
          /p:IncludeNativeLibrariesForSelfExtract=true `
          /p:InvariantGlobalization=false `
          /p:SatelliteResourceLanguages=ko-KR `
          /p:GenerateSatelliteAssembliesForUICulture=true `
          /p:UICulture=ko-KR `
          --verbosity detailed > publish.log
      shell: pwsh

    - name: Upload publish log
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: publish-log
        path: publish.log

    - name: Create Velopack package
      run: |
        $version = "${{ steps.version.outputs.VERSION }}"
        vpk pack `
          --packId ${{ env.PROJECT_NAME }} `
          --packVersion $version `
          --packDir ./publish `
          --mainExe ${{ env.PROJECT_NAME }}.exe
      shell: pwsh

    - name: Upload to GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        $version = "${{ steps.version.outputs.VERSION }}"
        $tagName = "v$version"
        vpk upload github `
          --repoUrl ${{ github.server_url }}/${{ github.repository }} `
          --publish `
          --releaseName "${{ env.PROJECT_NAME }} $version" `
          --tag $tagName `
          --token ${{ secrets.GIT_TOKEN }}
      shell: pwsh

#    - name: Upload artifacts
#      uses: actions/upload-artifact@v4
#      with:
#        name: velopack-package-${{ steps.version.outputs.VERSION }}
#        path: |
#          ./Releases/**/*
#          ./publish/**/*
#        retention-days: 30