// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpeechAgent.Database;

#nullable disable

namespace SpeechAgent.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251026002632_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("SpeechAgent.Database.Schemas.LocalSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomChartControlType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomChartIndex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomExeTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomImageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomImageRect")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomNameControlType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomNameIndex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetAppName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LocalSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
