// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpeechAgent.Database;

#nullable disable

namespace SpeechAgent.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("SpeechAgent.Database.Schemas.LocalSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomChartClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomChartIndex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomExeTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomImageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomImageRect")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomNameClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomNameIndex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetAppName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseAutomation")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LocalSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
